---
title: "CF_fgsea"
output: pdf_document
---

```{r}
library(fgsea)
library(data.table)
library(ggplot2)
library(tidyverse)
```

```{r cars}
# Illumina_ids_table <- read.table("~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Ogilvie/Data/Illumina_ids_table.csv",
#                                  sep = "\t",
#                                  header = T)
```

```{r}
# Ogilvie_nasal_norm <- read.table("/Users/matthieu/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Ogilvie/Data/normalised/Ogilvie_clean_nasal_normalised_counts_2022_01_24.txt",
#                                  sep = "\t",
#                                  header = T)
# 
# res_df <- read.table("~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Ogilvie/DE_Analysis/nasal/Ogilvie_nasal_differential_expression_analysis_limma_gene_id_2022_01_20.txt",
#                          sep = "\t",
#                          header = T)
# 
# 
# res_df <- merge(res_df,
#                 unique(Illumina_ids_table[,c("Target", "Symbol")]),
#                 by.x = "Gene_id",
#                 by.y = "Target",
#                 all.x = TRUE)
# 
# # Distinct way
# # Ogilvie_DEG <- Ogilvie_DEG %>% distinct(Symbol, .keep_all = TRUE)
# # Ogilvie_DEG <- Ogilvie_DEG[!is.na(Ogilvie_DEG$Symbol),]
# 
# res_df <- res_df[which(!is.na(res_df$Symbol)),]
# res_df <- res_df[which(res_df$Symbol!=""),]
# 
# HGNC_occ <- data.frame(table(res_df$Symbol))
# unique_genes <- HGNC_occ[which(HGNC_occ$Freq==1), "Var1"]
# 
# res_df_HGNC_unique <- res_df[which(res_df$Symbol %in% unique_genes),]
# 
# duplicated_genes <- unique(res_df[duplicated(res_df$Symbol), "Symbol"])
# 
# affy_id_to_keep <- sapply(duplicated_genes, function(gene){
#   affy_id <- res_df[which(res_df$Symbol==gene),"Gene_id"]
#   
#   data_gene <- Ogilvie_nasal_norm[affy_id,]
#   data_gene$mean <- rowMeans(data_gene, na.rm = TRUE)
#   data_gene$sd <- apply(data_gene,1, sd, na.rm = TRUE)
#   data_gene$threshold <- data_gene$mean/data_gene$sd
#   
#   affy_id_to_keep <- rownames(data_gene[which.max(data_gene$threshold),])
#   return(affy_id_to_keep)
# })
# res_df_HGNC_to_keep <- res_df[which(res_df$Gene_id %in% affy_id_to_keep),]
# 
# res_df_HGNC_final <- rbind(res_df_HGNC_unique,
#                           res_df_HGNC_to_keep)

# Previous way

# # Best P value way 
# HGNC_occ <- data.frame(table(Ogilvie_DEG$Symbol))
# unique_genes <- HGNC_occ[which(HGNC_occ$Freq==1), "Var1"]
# 
# # unique ones
# Ogilvie_DEG_HGNC_unique <- Ogilvie_DEG[which(Ogilvie_DEG$Symbol %in% unique_genes),]
# 
# # duplicated ones
# duplicated_genes <- unique(Ogilvie_DEG[duplicated(Ogilvie_DEG$Symbol), "Symbol"])
# 
# gene_id_to_keep <- sapply(duplicated_genes, function(gene){
#   Ogilvie_DEG_HGNC_gene <- Ogilvie_DEG[which(Ogilvie_DEG$Symbol==gene),]
#   affy_id_to_keep <- Ogilvie_DEG_HGNC_gene[which.min(Ogilvie_DEG_HGNC_gene$P.Value), "Gene_id"]
#   return(affy_id_to_keep)
# })
# Ogilvie_DEG_HGNC_to_keep <- Ogilvie_DEG[which(Ogilvie_DEG$Gene_id %in% gene_id_to_keep),]
# 
# Ogilvie_DEG_final <- rbind(Ogilvie_DEG_HGNC_unique,
#                           Ogilvie_DEG_HGNC_to_keep)


# write.table(res_df_HGNC_final,
#             file = "~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Ogilvie/DE_Analysis/nasal/Ogilvie_nasal_DEG_limma_unique_HGNC_2022_02_09.csv",
#             sep = "\t",
#             row.names = F)

res_df_HGNC_final <- read.table("~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Ogilvie/DE_Analysis/nasal/Ogilvie_nasal_DEG_limma_unique_HGNC_2022_02_09.csv",
                                sep = "\t",
                                header = T)

Ogilvie_stat <- res_df_HGNC_final[,c("Symbol", "t")]

ranks <- deframe(Ogilvie_stat)
```


```{r}
# pathways.hallmark <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/h.all.v7.4.symbols.gmt")
# all_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/all_pathways_2022_01_12.gmt")
all_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/kegg_from_omnipathR_gsea_2022_09_07.gmt")
kegg_pathways <- lapply(X = all_pathways, FUN = function(gene_list){
  return(gene_list[lapply(gene_list, nchar)>0])
})
```

```{r}
fgseaRes <- fgsea(pathways = dorothea_pathways, 
                  stats    = ranks,
                  minSize  = 0,
                  maxSize  = 500,
                  #nperm=10000,
                  eps=0.0)

save(fgseaRes,
     file = "~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Ogilvie/GSEA/Ogilvie_nasal_fgsea_report_dorothea_pathways_2022_09_07.RData")
# write.table(data.frame(fgseaRes[,-c("leadingEdge")]),
#             file = "~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Analyse Clarke/GSEA/Clarke_fgsea_report_2021_01_14.tsv",
#             sep = "\t")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r}
library(ggplot2)

density <- ggplot(fgseaRes, aes(x=pval))+
  geom_density()
```