---
title: "CF_fgsea"
output: pdf_document
---

```{r}
library(fgsea)
library(data.table)
library(ggplot2)
library(tidyverse)
```

```{r cars}
data(examplePathways)
data(exampleRanks)
set.seed(42)
```

```{r}
Voisin_DEG_HGNC <- read.table("~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Voisin/DE_Analysis/Voisin_DEG_limma_unique_HGNC_2021_02_08.txt",
                         sep = "\t",
                         header = T)

Voisin_stat <- Voisin_DEG_HGNC[,c("Symbol", "t")]

ranks <- deframe(Voisin_stat)
```


```{r}
# pathways.hallmark <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/h.all.v7.4.symbols.gmt")
# all_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/all_pathways_2022_01_12.gmt")
# all_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/wikipathways_filtered_gsea_2022_09_07.gmt")
# all_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/kegg_pathways_test_gsea_2022_09_07.gmt"
# all_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/kegg_from_omnipathR_gsea_2022_09_07.gmt")
# kegg_pathways <- lapply(X = all_pathways, FUN = function(gene_list){
#   return(gene_list[lapply(gene_list, nchar)>0])
# })
dorothea_pathways <- gmtPathways("~/ownCloud/Thèse/Systems Biology/gmt/dorothea_gsea_2022_01_12.gmt")
```

```{r}
fgseaRes <- fgsea(pathways = dorothea_pathways, 
                  stats    = ranks,
                  minSize  = 0,
                  maxSize  = 500,
                  # nperm=10000,
                  eps=0.0)

# save(fgseaRes,
#      file = "~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Transcriptomic Analyses/Analyse Voisin/GSEA/Voisin_fgsea_report_dorothea_pathways_2022_09_07.RData")
# # # write.table(data.frame(fgseaRes[,-c("leadingEdge")]),
# # #             file = "~/ownCloud/Thèse/Systems Biology/Transcriptomic studies/Analyse Clarke/GSEA/Clarke_fgsea_report_2021_01_14.tsv",
# # #             sep = "\t")
```

Meta-analysis transcriptomic pathways 

```{r}

```